name: Check PR

on:
  pull_request:
    branches: [ prod ]

jobs:
  check:
    name: Check PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Check eslint
        run: npm run lint:check

      - name: Typescript check
        run: npm run ts:check
